name: Plan Bundle
on:
  workflow_call:
    inputs:
      bundle:
        required: true
        type: string

permissions:
  contents: read

jobs:
  bundle_checks:
    name: ${{ inputs.bundle }} checks
    # LFAI needs to be on uds-ubuntu-big-boy-8-core due to filesystem space limitations on free runners
    #runs-on: "${{ inputs.bundle == 'lfai' && 'uds-ubuntu-big-boy-8-core' || 'ubuntu-latest'}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Setup runner
        shell: bash
        run: echo "[*] Setup runner"
        #run: uds run --no-progress setup-env

      - name: GHCR Login
        run: uds zarf tools registry login -u "dummy" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: Test creation of bundle
        shell: bash
        run: |
          echo "[*] Test creation of bundle"
          echo "inputs.bundle: ${{ inputs.bundle }}"
        #run: uds run --no-progress create-${{ inputs.bundle }}

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -${{ inputs.bundle }}-bundle-checks
